import { TarotCardEntity } from '../types';

/**
 * @link https://www.tarotcardmeanings.net/
 */

export const tarotCards: Record<string, TarotCardEntity> = {
  'tarot-chariot': {
    id: 'tarot-chariot',
    name: 'The Chariot',
    arcana: 'major',
    suit: null,
    character: 'James',
    archetype: 'conqueror',
    fortune: 'triumph in spite of resistance',
    upright: '',
    reversed: '',
  },
  'tarot-cups-01': {
    id: 'tarot-cups-01',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Mary',
    archetype: 'drastic change of feelings',
    fortune: 'solace and bliss around the corner',
    upright: '',
    reversed: '',
  },
  'tarot-cups-02': {
    id: 'tarot-cups-02',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Robert',
    archetype: 'bond',
    fortune: 'great pleasure in sharing with others',
    upright: '',
    reversed: '',
  },
  'tarot-cups-03': {
    id: 'tarot-cups-03',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Patricia',
    archetype: 'festivity',
    fortune: 'a time of festivity and celebration',
    upright: '',
    reversed: '',
  },
  'tarot-cups-04': {
    id: 'tarot-cups-04',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'John',
    archetype: 'melancholia',
    fortune: 'pleasure to melencholia',
    upright: 'give them what they wanted',
    reversed: 'take what they have for granted',
  },
  'tarot-cups-05': {
    id: 'tarot-cups-05',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Jennifer',
    archetype: 'despair',
    fortune: 'life to lose its taste but dissolve eventually',
    upright: '',
    reversed: '',
  },
  'tarot-cups-06': {
    id: 'tarot-cups-06',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Michael',
    archetype: 'happiness',
    fortune: 'to cherish the moment for joy and happiness',
    upright: '',
    reversed: '',
  },
  'tarot-cups-07': {
    id: 'tarot-cups-07',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Linda',
    archetype: 'temptation',
    fortune: 'temptation and its spice of hunger',
    upright: '',
    reversed: '',
  },
  'tarot-cups-08': {
    id: 'tarot-cups-08',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'William',
    archetype: 'disgust',
    fortune: 'a bitter aftertaste to maturity',
    upright: '',
    reversed: '',
  },
  'tarot-cups-09': {
    id: 'tarot-cups-09',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Elizabeth',
    archetype: 'gluttony',
    fortune: 'gluttony and complacency of the mind',
    upright: 'make a sacrifice to achieve a larger goal',
    reversed: 'indulge in excess towards a dream',
  },
  'tarot-cups-10': {
    id: 'tarot-cups-10',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'David',
    archetype: 'bliss',
    fortune: 'bliss of accomplishment and reward of the worthy',
    upright: '',
    reversed: '',
  },
  'tarot-cups-11': {
    id: 'tarot-cups-11',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Barbara',
    archetype: 'comforting friend',
    fortune: 'to be surprised and amused at the irony of it all',
    upright: 'spend money wisely',
    reversed: 'spend money carelessly',
  },
  'tarot-cups-12': {
    id: 'tarot-cups-12',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Richard',
    archetype: 'emotional advancement',
    fortune: 'pride and the strength of protection',
    upright: '',
    reversed: '',
  },
  'tarot-cups-13': {
    id: 'tarot-cups-13',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Susan',
    archetype: 'settling emotions',
    fortune: 'to be stuck in obsession by the mind',
    upright: 'steady in focusing the mind',
    reversed: 'wallow in self-pity',
  },
  'tarot-cups-14': {
    id: 'tarot-cups-14',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Joseph',
    archetype: 'emotional restraint',
    fortune: 'to take nothing for granted, not even yourself',
    upright: '',
    reversed: '',
  },
  'tarot-death': {
    id: 'tarot-death',
    name: 'Death',
    arcana: 'major',
    suit: null,
    character: 'Jessica',
    archetype: 'grim reaper',
    fortune: 'a coming to an end or loss',
    upright: 'let go',
    reversed: 'hold tight',
  },
  'tarot-devil': {
    id: 'tarot-devil',
    name: 'The Devil',
    arcana: 'major',
    suit: null,
    character: 'Thomas',
    archetype: 'archfiend',
    fortune: 'pain and delight of giving in to temptation',
    upright: '',
    reversed: '',
  },
  'tarot-emperor': {
    id: 'tarot-emperor',
    name: 'The Emperor',
    arcana: 'major',
    suit: null,
    character: 'Sarah',
    archetype: 'supreme ruler',
    fortune: 'to yield in face of irresistible power',
    upright: '',
    reversed: '',
  },
  'tarot-empress': {
    id: 'tarot-empress',
    name: 'The Empress',
    arcana: 'major',
    suit: null,
    character: 'Charles',
    archetype: 'benefactor',
    fortune: 'gentle power in your favor',
    upright: '',
    reversed: '',
  },
  'tarot-fool': {
    id: 'tarot-fool',
    name: 'The Fool',
    arcana: 'major',
    suit: null,
    character: 'Karen',
    archetype: 'innocence',
    fortune: 'Blissful carelessness and the power of ignorance',
    upright: '',
    reversed: '',
  },
  'tarot-hangedman': {
    id: 'tarot-hangedman',
    name: 'The Hanged Man',
    arcana: 'major',
    suit: null,
    character: 'Christopher',
    archetype: 'martyr',
    fortune: 'resilience from great personal sacrifice',
    upright: '',
    reversed: '',
  },
  'tarot-hermit': {
    id: 'tarot-hermit',
    name: 'The Hermit',
    arcana: 'major',
    suit: null,
    character: 'Nancy',
    archetype: 'solitude',
    fortune: 'lesson and reward, but also misfortune, of solitude',
    upright: '',
    reversed: '',
  },
  'tarot-hierophant': {
    id: 'tarot-hierophant',
    name: 'The Hierophant',
    arcana: 'major',
    suit: null,
    character: 'Daniel',
    archetype: 'priest',
    fortune: 'dependency on elevated dignity',
    upright: '',
    reversed: '',
  },
  'tarot-highpriestess': {
    id: 'tarot-highpriestess',
    name: 'The High Priestess',
    arcana: 'major',
    suit: null,
    character: 'Lisa',
    archetype: 'secret',
    fortune: 'elucidation of secrets and hidden circumstances',
    upright: '',
    reversed: '',
  },
  'tarot-judgement': {
    id: 'tarot-judgement',
    name: 'Judgement',
    arcana: 'major',
    suit: null,
    character: 'Matthew',
    archetype: 'result',
    fortune: 'the arrival of ultimate judgment',
    upright: '',
    reversed: '',
  },
  'tarot-justice': {
    id: 'tarot-justice',
    name: 'Justice',
    arcana: 'major',
    suit: null,
    character: 'Betty',
    archetype: 'judge',
    fortune: 'justice and the blindfold of fairness',
    upright: '',
    reversed: '',
  },
  'tarot-lovers': {
    id: 'tarot-lovers',
    name: 'The Lovers',
    arcana: 'major',
    suit: null,
    character: 'Anthony',
    archetype: 'love',
    fortune: 'deeply felt mutual attraction, for as long as it lasts',
    upright: '',
    reversed: '',
  },
  'tarot-magician': {
    id: 'tarot-magician',
    name: 'The Magician',
    arcana: 'major',
    suit: null,
    character: 'Margaret',
    archetype: 'wizard',
    fortune: 'sudden solution by magic or illusion',
    upright: '',
    reversed: '',
  },
  'tarot-moon': {
    id: 'tarot-moon',
    name: 'The Moon',
    arcana: 'major',
    suit: null,
    character: 'Mark',
    archetype: 'soul',
    fortune: 'longing for the sake of longing',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-01': {
    id: 'tarot-pentacles-01',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Sandra',
    archetype: 'drastic change of thought',
    fortune: 'a contemplation and the formation of an idea',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-02': {
    id: 'tarot-pentacles-02',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Donald',
    archetype: 'confusion',
    fortune: 'a paradox that appears insoluble',
    upright: 'juggle resources to make ends meet',
    reversed: 'neglect resources and go into debt',
  },
  'tarot-pentacles-03': {
    id: 'tarot-pentacles-03',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Ashley',
    archetype: 'pondering',
    fortune: 'an uncertainty of realism or imagery',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-04': {
    id: 'tarot-pentacles-04',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Steven',
    archetype: 'self-obsession',
    fortune: 'to be caught by the brilliance of your own thinking',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-05': {
    id: 'tarot-pentacles-05',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kimberly',
    archetype: 'destitution',
    fortune: 'struggle against old lines of thought',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-06': {
    id: 'tarot-pentacles-06',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Paul',
    archetype: 'generosity',
    fortune: 'surplus and proper modesty',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-07': {
    id: 'tarot-pentacles-07',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Emily',
    archetype: 'contemplation',
    fortune: 'splendid ideas of prosperity',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-08': {
    id: 'tarot-pentacles-08',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Andrew',
    archetype: 'skill',
    fortune: 'the work, the plan, and the preparation',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-09': {
    id: 'tarot-pentacles-09',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Donna',
    archetype: 'prosperity',
    fortune: 'prosperity in so many ways',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-10': {
    id: 'tarot-pentacles-10',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Joshua',
    archetype: 'wisdom',
    fortune: 'stimulation, wisdom, and knowledge for inspiration',
    upright: 'shower friends and family with gifts',
    reversed: 'withhold gifts from friends and family',
  },
  'tarot-pentacles-11': {
    id: 'tarot-pentacles-11',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Michelle',
    archetype: 'agreeing friend',
    fortune: 'invigoration and optimism of new possibilities',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-12': {
    id: 'tarot-pentacles-12',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kenneth',
    archetype: 'intellectual advancement',
    fortune: 'the course and the plan to reach your goal',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-13': {
    id: 'tarot-pentacles-13',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Dorothy',
    archetype: 'settling mind',
    fortune: 'the need for ponderment and personal growth',
    upright: '',
    reversed: '',
  },
  'tarot-pentacles-14': {
    id: 'tarot-pentacles-14',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kevin',
    archetype: 'intellectual prominence',
    fortune: 'key to success is holding on to it',
    upright: '',
    reversed: '',
  },
  'tarot-star': {
    id: 'tarot-star',
    name: 'The Star',
    arcana: 'major',
    suit: null,
    character: 'Carol',
    archetype: 'distance',
    fortune: 'a Time to pause and reflect',
    upright: '',
    reversed: '',
  },
  'tarot-strength': {
    id: 'tarot-strength',
    name: 'Strength',
    arcana: 'major',
    suit: null,
    character: 'Brian',
    archetype: 'hero',
    fortune: 'clever application leads to superior stregnth',
    upright: '',
    reversed: '',
  },
  'tarot-sun': {
    id: 'tarot-sun',
    name: 'The Sun',
    arcana: 'major',
    suit: null,
    character: 'Amanda',
    archetype: 'ability',
    fortune: 'great resources at your disposal',
    upright: '',
    reversed: '',
  },
  'tarot-swords-01': {
    id: 'tarot-swords-01',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'George',
    archetype: 'drastic change of action',
    fortune: 'imminent need of stern action',
    upright: 'make decisions with consideration of the consequences',
    reversed: 'make decisions without considering the consequences.',
  },
  'tarot-swords-02': {
    id: 'tarot-swords-02',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Melissa',
    archetype: 'crossroads',
    fortune: 'a hasty decision in both directions',
    upright: '',
    reversed: '',
  },
  'tarot-swords-03': {
    id: 'tarot-swords-03',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Edward',
    archetype: 'separation',
    fortune: 'take no step before heeding the warning',
    upright: '',
    reversed: '',
  },
  'tarot-swords-04': {
    id: 'tarot-swords-04',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Deborah',
    archetype: 'commemoration',
    fortune: 'to be remembered for your action',
    upright: '',
    reversed: '',
  },
  'tarot-swords-05': {
    id: 'tarot-swords-05',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Ronald',
    archetype: 'desertion',
    fortune: 'betrayal when the battle is over',
    upright: '',
    reversed: '',
  },
  'tarot-swords-06': {
    id: 'tarot-swords-06',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Stephanie',
    archetype: 'loss',
    fortune: 'a most costly outcome of a large venture',
    upright: '',
    reversed: '',
  },
  'tarot-swords-07': {
    id: 'tarot-swords-07',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Timothy',
    archetype: 'betrayal',
    fortune: 'a sudden distant to victory',
    upright: '',
    reversed: '',
  },
  'tarot-swords-08': {
    id: 'tarot-swords-08',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Rebecca',
    archetype: 'victim',
    fortune: 'helplesslness in the hands of others',
    upright: '',
    reversed: '',
  },
  'tarot-swords-09': {
    id: 'tarot-swords-09',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Jason',
    archetype: 'anguish',
    fortune: 'inevitable responsibility of choices made',
    upright: '',
    reversed: '',
  },
  'tarot-swords-10': {
    id: 'tarot-swords-10',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Sharon',
    archetype: 'defeat',
    fortune: 'blamelessness at utter defeat and suffering',
    upright: '',
    reversed: '',
  },
  'tarot-swords-11': {
    id: 'tarot-swords-11',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Jeffrey',
    archetype: 'allied friend',
    fortune: 'bravery to win at all cost',
    upright: '',
    reversed: '',
  },
  'tarot-swords-12': {
    id: 'tarot-swords-12',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Laura',
    archetype: 'advancement in action',
    fortune: 'to charge ahead regardless of consequences',
    upright: '',
    reversed: '',
  },
  'tarot-swords-13': {
    id: 'tarot-swords-13',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Ryan',
    archetype: 'settling calamity',
    fortune: 'mighty power and its usage in battle',
    upright: '',
    reversed: '',
  },
  'tarot-swords-14': {
    id: 'tarot-swords-14',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Cynthia',
    archetype: 'decisive action',
    fortune: 'acceptance of change, regardless of outcomes',
    upright: '',
    reversed: '',
  },
  'tarot-temperance': {
    id: 'tarot-temperance',
    name: 'Temperance',
    arcana: 'major',
    suit: null,
    character: 'Jacob',
    archetype: 'patience',
    fortune: 'moderation to be the ultimate persistence',
    upright: '',
    reversed: '',
  },
  'tarot-tower': {
    id: 'tarot-tower',
    name: 'The Tower',
    arcana: 'major',
    suit: null,
    character: 'Kathleen',
    archetype: 'destruction',
    fortune: 'a spectacular ambition that ends with disaster',
    upright: '',
    reversed: '',
  },
  'tarot-wands-01': {
    id: 'tarot-wands-01',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Gary',
    archetype: 'drastic material change',
    fortune: 'a significant change of material matters',
    upright: '',
    reversed: '',
  },
  'tarot-wands-02': {
    id: 'tarot-wands-02',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Amy',
    archetype: 'ambition',
    fortune: 'a longing of the world',
    upright: '',
    reversed: '',
  },
  'tarot-wands-03': {
    id: 'tarot-wands-03',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Nicholas',
    archetype: 'obsolete',
    fortune: 'to miss the world and all the good things it has offered',
    upright: '',
    reversed: '',
  },
  'tarot-wands-04': {
    id: 'tarot-wands-04',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Shirley',
    archetype: 'celebration',
    fortune: 'returning from the world, enriched and pleased',
    upright: '',
    reversed: '',
  },
  'tarot-wands-05': {
    id: 'tarot-wands-05',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Eric',
    archetype: 'calamity',
    fortune: 'a costly decision when ambitions collide',
    upright: '',
    reversed: '',
  },
  'tarot-wands-06': {
    id: 'tarot-wands-06',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Angela',
    archetype: 'success',
    fortune: 'great gains in material matters',
    upright: '',
    reversed: '',
  },
  'tarot-wands-07': {
    id: 'tarot-wands-07',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Jonathan',
    archetype: 'competition',
    fortune: 'to struggle to hold on to what you have',
    upright: '',
    reversed: '',
  },
  'tarot-wands-08': {
    id: 'tarot-wands-08',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Helen',
    archetype: 'obstacles',
    fortune: 'hard work to reach your goals',
    upright: '',
    reversed: '',
  },
  'tarot-wands-09': {
    id: 'tarot-wands-09',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Stephen',
    archetype: 'recovery',
    fortune: 'to be overwhelmed but rise again',
    upright: 'refuse to quit',
    reversed: 'accept defeat',
  },
  'tarot-wands-10': {
    id: 'tarot-wands-10',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Anna',
    archetype: 'strain',
    fortune: "unreasonable workload but there's reward ahead",
    upright: '',
    reversed: '',
  },
  'tarot-wands-11': {
    id: 'tarot-wands-11',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Larry',
    archetype: 'helpful friend',
    fortune: 'plenty of possibilities but wait no longer',
    upright: '',
    reversed: '',
  },
  'tarot-wands-12': {
    id: 'tarot-wands-12',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Brenda',
    archetype: 'material advancement',
    fortune: 'stand your ground on great promises of success',
    upright: '',
    reversed: '',
  },
  'tarot-wands-13': {
    id: 'tarot-wands-13',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Justin',
    archetype: 'settling with possessions',
    fortune: 'staleness to withering and decisions to profit',
    upright: '',
    reversed: '',
  },
  'tarot-wands-14': {
    id: 'tarot-wands-14',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Pamela',
    archetype: 'material wealth',
    fortune: 'the prosperity of weath and the poison of wealth',
    upright: '',
    reversed: '',
  },
  'tarot-wheeloffortune': {
    id: 'tarot-wheeloffortune',
    name: 'Wheel of Fortune',
    arcana: 'major',
    suit: null,
    character: 'Scott',
    archetype: 'chance',
    fortune: 'an uncertain outcome and careful consideration',
    upright: '',
    reversed: '',
  },
  'tarot-world': {
    id: 'tarot-world',
    name: 'The World',
    arcana: 'major',
    suit: null,
    character: 'Nicole',
    archetype: 'opportunity',
    fortune: 'opportunities at your hand',
    upright: 'avoid indulgence and excess',
    reversed: 'blind by greed and envy',
  },
};
