import { TarotCardEntity } from '../types';

/**
 * @link https://www.tarotcardmeanings.net/
 */

export const tarotCards: Record<string, TarotCardEntity> = {
  'tarot-chariot': {
    id: 'tarot-chariot',
    name: 'The Chariot',
    arcana: 'major',
    suit: null,
    character: 'James',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-01': {
    id: 'tarot-cups-01',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Mary',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-02': {
    id: 'tarot-cups-02',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Robert',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-03': {
    id: 'tarot-cups-03',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Patricia',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-04': {
    id: 'tarot-cups-04',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'John',
    upright: 'give them what they wanted',
    reversed: 'take what they have for granted',
    fortune: 'TODO',
  },
  'tarot-cups-05': {
    id: 'tarot-cups-05',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Jennifer',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-06': {
    id: 'tarot-cups-06',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Michael',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-07': {
    id: 'tarot-cups-07',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Linda',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-08': {
    id: 'tarot-cups-08',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'William',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-09': {
    id: 'tarot-cups-09',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Elizabeth',
    upright: 'make a sacrifice to achieve a larger goal',
    reversed: 'indulge in excess towards a dream',
    fortune: 'TODO',
  },
  'tarot-cups-10': {
    id: 'tarot-cups-10',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'David',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-11': {
    id: 'tarot-cups-11',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Barbara',
    upright: 'spend money wiseley',
    reversed: 'spend money carelessly',
    fortune: 'TODO',
  },
  'tarot-cups-12': {
    id: 'tarot-cups-12',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Richard',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-13': {
    id: 'tarot-cups-13',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Susan',
    upright: 'steady in focusing the mind',
    reversed: 'wallow in self-pity',
    fortune: 'TODO',
  },
  'tarot-cups-14': {
    id: 'tarot-cups-14',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: 'Joseph',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-death': {
    id: 'tarot-death',
    name: 'Death',
    arcana: 'major',
    suit: null,
    character: 'Jessica',
    upright: 'let go',
    reversed: 'hold tight',
    fortune: 'TODO',
  },
  'tarot-devil': {
    id: 'tarot-devil',
    name: 'The Devil',
    arcana: 'major',
    suit: null,
    character: 'Thomas',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-emperor': {
    id: 'tarot-emperor',
    name: 'The Emperor',
    arcana: 'major',
    suit: null,
    character: 'Sarah',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-empress': {
    id: 'tarot-empress',
    name: 'The Empress',
    arcana: 'major',
    suit: null,
    character: 'Charles',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-fool': {
    id: 'tarot-fool',
    name: 'The Fool',
    arcana: 'major',
    suit: null,
    character: 'Karen',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hangedman': {
    id: 'tarot-hangedman',
    name: 'The Hanged Man',
    arcana: 'major',
    suit: null,
    character: 'Christopher',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hermit': {
    id: 'tarot-hermit',
    name: 'The Hermit',
    arcana: 'major',
    suit: null,
    character: 'Nancy',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hierophant': {
    id: 'tarot-hierophant',
    name: 'The Hierophant',
    arcana: 'major',
    suit: null,
    character: 'Daniel',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-highpriestess': {
    id: 'tarot-highpriestess',
    name: 'The High Priestess',
    arcana: 'major',
    suit: null,
    character: 'Lisa',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-judgement': {
    id: 'tarot-judgement',
    name: 'Judgement',
    arcana: 'major',
    suit: null,
    character: 'Matthew',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-justice': {
    id: 'tarot-justice',
    name: 'Justice',
    arcana: 'major',
    suit: null,
    character: 'Betty',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-lovers': {
    id: 'tarot-lovers',
    name: 'The Lovers',
    arcana: 'major',
    suit: null,
    character: 'Anthony',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-magician': {
    id: 'tarot-magician',
    name: 'The Magician',
    arcana: 'major',
    suit: null,
    character: 'Margaret',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-moon': {
    id: 'tarot-moon',
    name: 'The Moon',
    arcana: 'major',
    suit: null,
    character: 'Mark',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-01': {
    id: 'tarot-pentacles-01',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Sandra',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-02': {
    id: 'tarot-pentacles-02',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Donald',
    upright: 'juggle resources to make ends meet',
    reversed: 'neglect resources and go into debt',
    fortune: 'TODO',
  },
  'tarot-pentacles-03': {
    id: 'tarot-pentacles-03',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Ashley',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-04': {
    id: 'tarot-pentacles-04',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Steven',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-05': {
    id: 'tarot-pentacles-05',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kimberly',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-06': {
    id: 'tarot-pentacles-06',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Paul',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-07': {
    id: 'tarot-pentacles-07',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Emily',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-08': {
    id: 'tarot-pentacles-08',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Andrew',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-09': {
    id: 'tarot-pentacles-09',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Donna',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-10': {
    id: 'tarot-pentacles-10',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Joshua',
    upright: 'shower friends and family with gifts',
    reversed: 'withhold gifts from friends and family',
    fortune: 'TODO',
  },
  'tarot-pentacles-11': {
    id: 'tarot-pentacles-11',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Michelle',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-12': {
    id: 'tarot-pentacles-12',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kenneth',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-13': {
    id: 'tarot-pentacles-13',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Dorothy',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-14': {
    id: 'tarot-pentacles-14',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: 'Kevin',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-star': {
    id: 'tarot-star',
    name: 'The Star',
    arcana: 'major',
    suit: null,
    character: 'Carol',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-strength': {
    id: 'tarot-strength',
    name: 'Strength',
    arcana: 'major',
    suit: null,
    character: 'Brian',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-sun': {
    id: 'tarot-sun',
    name: 'The Sun',
    arcana: 'major',
    suit: null,
    character: 'Amanda',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-01': {
    id: 'tarot-swords-01',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'George',
    upright: 'make decisions with consideration of the consequences',
    reversed: 'make decisions without considering the consequences.',
    fortune: 'TODO',
  },
  'tarot-swords-02': {
    id: 'tarot-swords-02',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Melissa',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-03': {
    id: 'tarot-swords-03',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Edward',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-04': {
    id: 'tarot-swords-04',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Deborah',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-05': {
    id: 'tarot-swords-05',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Ronald',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-06': {
    id: 'tarot-swords-06',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Stephanie',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-07': {
    id: 'tarot-swords-07',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Timothy',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-08': {
    id: 'tarot-swords-08',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Rebecca',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-09': {
    id: 'tarot-swords-09',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Jason',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-10': {
    id: 'tarot-swords-10',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Sharon',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-11': {
    id: 'tarot-swords-11',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Jeffrey',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-12': {
    id: 'tarot-swords-12',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Laura',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-13': {
    id: 'tarot-swords-13',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Ryan',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-14': {
    id: 'tarot-swords-14',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: 'Cynthia',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-temperance': {
    id: 'tarot-temperance',
    name: 'Temperance',
    arcana: 'major',
    suit: null,
    character: 'Jacob',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-tower': {
    id: 'tarot-tower',
    name: 'The Tower',
    arcana: 'major',
    suit: null,
    character: 'Kathleen',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-01': {
    id: 'tarot-wands-01',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Gary',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-02': {
    id: 'tarot-wands-02',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Amy',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-03': {
    id: 'tarot-wands-03',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Nicholas',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-04': {
    id: 'tarot-wands-04',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Shirley',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-05': {
    id: 'tarot-wands-05',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Eric',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-06': {
    id: 'tarot-wands-06',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Angela',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-07': {
    id: 'tarot-wands-07',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Jonathan',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-08': {
    id: 'tarot-wands-08',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Helen',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-09': {
    id: 'tarot-wands-09',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Stephen',
    upright: 'refuse to quit',
    reversed: 'accept defeat',
    fortune: 'overwhelmed by many but expect to rise again',
  },
  'tarot-wands-10': {
    id: 'tarot-wands-10',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Anna',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-11': {
    id: 'tarot-wands-11',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Larry',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-12': {
    id: 'tarot-wands-12',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Brenda',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-13': {
    id: 'tarot-wands-13',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Justin',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-14': {
    id: 'tarot-wands-14',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: 'Pamela',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wheeloffortune': {
    id: 'tarot-wheeloffortune',
    name: 'Wheel of Fortune',
    arcana: 'major',
    suit: null,
    character: 'Scott',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-world': {
    id: 'tarot-world',
    name: 'The World',
    arcana: 'major',
    suit: null,
    character: 'Nicole',
    upright: 'aware by cost and price',
    reversed: 'blind by greed and envy',
    fortune: 'TODO',
  },
};
