import { TarotCardEntity } from '../types';

/**
 * @link https://www.tarotcardmeanings.net/
 */

export const tarotCards: Record<string, TarotCardEntity> = {
  'tarot-chariot': {
    id: 'tarot-chariot',
    name: 'The Chariot',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-01': {
    id: 'tarot-cups-01',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-02': {
    id: 'tarot-cups-02',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-03': {
    id: 'tarot-cups-03',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-04': {
    id: 'tarot-cups-04',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-05': {
    id: 'tarot-cups-05',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-06': {
    id: 'tarot-cups-06',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-07': {
    id: 'tarot-cups-07',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-08': {
    id: 'tarot-cups-08',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-09': {
    id: 'tarot-cups-09',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-10': {
    id: 'tarot-cups-10',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-11': {
    id: 'tarot-cups-11',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-12': {
    id: 'tarot-cups-12',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-13': {
    id: 'tarot-cups-13',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-cups-14': {
    id: 'tarot-cups-14',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-death': {
    id: 'tarot-death',
    name: 'Death',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-devil': {
    id: 'tarot-devil',
    name: 'The Devil',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-emperor': {
    id: 'tarot-emperor',
    name: 'The Emperor',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-empress': {
    id: 'tarot-empress',
    name: 'The Empress',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-fool': {
    id: 'tarot-fool',
    name: 'The Fool',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hangedman': {
    id: 'tarot-hangedman',
    name: 'The Hanged Man',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hermit': {
    id: 'tarot-hermit',
    name: 'The Hermit',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-hierophant': {
    id: 'tarot-hierophant',
    name: 'The Hierophant',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-highpriestess': {
    id: 'tarot-highpriestess',
    name: 'The High Priestess',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-judgement': {
    id: 'tarot-judgement',
    name: 'Judgement',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-justice': {
    id: 'tarot-justice',
    name: 'Justice',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-lovers': {
    id: 'tarot-lovers',
    name: 'The Lovers',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-magician': {
    id: 'tarot-magician',
    name: 'The Magician',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-moon': {
    id: 'tarot-moon',
    name: 'The Moon',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-01': {
    id: 'tarot-pentacles-01',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-02': {
    id: 'tarot-pentacles-02',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-03': {
    id: 'tarot-pentacles-03',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-04': {
    id: 'tarot-pentacles-04',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-05': {
    id: 'tarot-pentacles-05',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-06': {
    id: 'tarot-pentacles-06',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-07': {
    id: 'tarot-pentacles-07',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-08': {
    id: 'tarot-pentacles-08',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-09': {
    id: 'tarot-pentacles-09',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-10': {
    id: 'tarot-pentacles-10',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-11': {
    id: 'tarot-pentacles-11',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-12': {
    id: 'tarot-pentacles-12',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-13': {
    id: 'tarot-pentacles-13',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-pentacles-14': {
    id: 'tarot-pentacles-14',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-star': {
    id: 'tarot-star',
    name: 'The Star',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-strength': {
    id: 'tarot-strength',
    name: 'Strength',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-sun': {
    id: 'tarot-sun',
    name: 'The Sun',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-01': {
    id: 'tarot-swords-01',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-02': {
    id: 'tarot-swords-02',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-03': {
    id: 'tarot-swords-03',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-04': {
    id: 'tarot-swords-04',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-05': {
    id: 'tarot-swords-05',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-06': {
    id: 'tarot-swords-06',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-07': {
    id: 'tarot-swords-07',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-08': {
    id: 'tarot-swords-08',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-09': {
    id: 'tarot-swords-09',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-10': {
    id: 'tarot-swords-10',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-11': {
    id: 'tarot-swords-11',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-12': {
    id: 'tarot-swords-12',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-13': {
    id: 'tarot-swords-13',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-swords-14': {
    id: 'tarot-swords-14',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-temperance': {
    id: 'tarot-temperance',
    name: 'Temperance',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-tower': {
    id: 'tarot-tower',
    name: 'The Tower',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-01': {
    id: 'tarot-wands-01',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-02': {
    id: 'tarot-wands-02',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-03': {
    id: 'tarot-wands-03',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-04': {
    id: 'tarot-wands-04',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-05': {
    id: 'tarot-wands-05',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-06': {
    id: 'tarot-wands-06',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-07': {
    id: 'tarot-wands-07',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-08': {
    id: 'tarot-wands-08',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-09': {
    id: 'tarot-wands-09',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-10': {
    id: 'tarot-wands-10',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-11': {
    id: 'tarot-wands-11',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-12': {
    id: 'tarot-wands-12',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-13': {
    id: 'tarot-wands-13',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wands-14': {
    id: 'tarot-wands-14',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-wheeloffortune': {
    id: 'tarot-wheeloffortune',
    name: 'Wheel of Fortune',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
  'tarot-world': {
    id: 'tarot-world',
    name: 'The World',
    arcana: 'major',
    suit: null,
    character: '',
    upright: '',
    reversed: '',
    fortune: '',
  },
};
